Algoritmo ALTO_BAJO
	DEFINIR N1,N2 COMO ENTERO;
	ESCRIBIR "INGRESE UN NÚMERO";
	LEER N1;
	ESCRIBIR "INGRESE UN NÚMERO";
	LEER N2;
	SI N1>N2 Entonces
		ESCRIBIR "EL NÚMERO ",N1," ES MAYOR QUE ",N2,;
	SiNo
		ESCRIBIR "EL NÚMERO ",N1," ES MENOR QUE ",N2; 
	FinSi
FinAlgoritmo
