Algoritmo DIVISIÓN
	DEFINIR N1,N2,DIV COMO REAL;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N1;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N2;
	SI N1<>0 Y N2<>0 Entonces
		DIV<-N1/N2
		ESCRIBIR "EL RESULTADO DE LA DIVISIÓN ENTRE ",N1," Y ",N2," ES DE: ",DIV;
	SiNo
		ESCRIBIR "ESCRIBIR UN NÚMERO DISTINTO DE CERO";
		
	FinSi
FinAlgoritmo
