Algoritmo EJ6
	DEFINIR LETRA Como Caracter;
	ESCRIBIR "INGRESAR UNA LETRA";
	LEER LETRA;
	SI LETRA== Mayusculas(LETRA) Entonces
		ESCRIBIR "LA LETRA ES MAYÚSCULA";
	SINO 
		ESCRIBIR "LA LETRA ES MINUSCULA";
	FinSi
FinAlgoritmo
