Algoritmo EJE13
	DEFINIR DIA,ANO,MES Como Entero;
	ESCRIBIR "INGRESE EL NÚMERO QUE CORRESPONDE AL DÍA";
	LEER DIA;
	ESCRIBIR "INGRESE EL NÚMERO QUE CORRESPONDE AL MES";
	LEER MES;
	ESCRIBIR "INGRESE EL NÚMERO QUE CORRESPONDE AL AÑO";
	LEER ANO;
	SI DIA>=1 Y DIA<=31 Y MES>=1 Y MES<=12 Y ANO=2022 ENTONCES 
		ESCRIBIR "LA FECHA ",DIA,"/",MES,"/",ANO," ES CORRECTA";
	SiNo
		ESCRIBIR "LA FECHA INGRESADA ES INCORRECTA";
	FinSi
	
FinAlgoritmo
