Algoritmo POSITIVO_NEGATIVO_CERO
	DEFINIR NUM COMO ENTERO;
	ESCRIBIR "INGRESA UN NÚMERO"
	LEER NUM;
	SI NUM>0 Entonces
		ESCRIBIR"EL NÚMERO ",NUM," ES POSITIVO"
	SINO 
		SI (NUM<0)
			ESCRIBIR "EL NÚMERO ",NUM," ES NEGATIVO"
		SINO 
			SI (NUM=0)
				ESCRIBIR "EL NÚMERO ES CERO"
			FinSi
		FinSi
	FinSi
FinAlgoritmo
