Algoritmo EJE15
	DEFINIR PAGO, PAGOACUM Como Real;
	DEFINIR MES Como Entero;
	PAGO=10;
	PAGOACUM=0;
	PARA MES<-1 HASTA 20 Hacer
		PAGOACUM=PAGOACUM+PAGO;
		PAGO=PAGO*2;
	FinPara
	ESCRIBIR "EL TOTAL QUE PAGÓ LUEGO DE LOS 20 MESES ES DE: ",PAGOACUM," $";
FinAlgoritmo
