Algoritmo FACTORIAL
	DEFINIR NUM, X,FACTOR Como Entero;
	FACTOR<-1
	ESCRIBIR "INGRESAR EL NÚMERO AL CUAL DESEE CALCULAR SU FACTORIAL"
	LEER NUM
	Para X=1 Hasta NUM Con Paso  1 Hacer
		FACTOR<-FACTOR*X
		
	Fin Para
ESCRIBIR "EL FACTORIAL DEL NÚMERO ",NUM," ES: ",FACTOR;	

FinAlgoritmo
