Algoritmo EJ8
	DEFINIR SUELDOBAS,COMIS,VENTA,SUELDOTOTAL Como Real;
	ESCRIBIR "INGRESAR EL VALOR DE SU SUELDO BASE";
	LEER SUELDOBAS;
	ESCRIBIR "INGRESAR EL TOTAL DE VENTAS EN EL MES";
	LEER VENTA;
	COMIS<-VENTA*0.1;
	SUELDOTOTAL<-COMIS+SUELDOBAS;
	ESCRIBIR "SU INGRESO EXTRA DE COMISIÓN ES DE: ",COMIS," $";
	ESCRIBIR "EL SUELDO DE ESTE MES ES DE: ",SUELDOTOTAL," $";
	
FinAlgoritmo
