Algoritmo EJ9
	DEFINIR DINGASTADO, TOTAL COMO REAL;
	ESCRIBIR "INGRESE EL MONTO QUE GASTÓ EN LA COMPRA";
	LEER DINGASTADO;
	TOTAL<-DINGASTADO-(DINGASTADO*0.15);
	ESCRIBIR "EL MONTO TOTAL A PAGAR ES DE: ",TOTAL," $";
	
FinAlgoritmo
