Algoritmo EJE11
	DEFINIR N1,N2,DISTANCIA Como Real;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N1;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N2;
	DISTANCIA<-N1-N2;
	ESCRIBIR "LA DISTANCIA ENTRE ",N1," Y ",N2, " ES DE: ",DISTANCIA;
	
FinAlgoritmo
