Algoritmo EJE14
	DEFINIR N1,A,B,RESUL Como Entero;
	ESCRIBIR"INGRESAR UN NÚMERO DE DOS CIFRAS";
	LEER N1;
	A=TRUNC(N1/10);
	B=N1 MOD 10;
	RESUL=B*10+A;
	ESCRIBIR N1," INVERTIDO ES: ",RESUL;
	
FinAlgoritmo
