Algoritmo EJE12
	DEFINIR X1,Y1,X2,Y2,DISTANCIA Como Real;
	ESCRIBIR " INGRESAR DOS NÚMEROS";
	LEER X1,Y1;
	ESCRIBIR "INGRESAR DOS NÚMEROS";
	LEER X2,Y2;
	DISTANCIA=raiz((X2-X1)^2+(Y2-Y1)^2);
	ESCRIBIR "LA DISTANCIA ENTRE EL PUNTO ",X1," , ", Y1," Y EL PUNTO ",X2," , ",Y2," ES DE: ",DISTANCIA;
	
	
FinAlgoritmo
