Algoritmo EJE16
	DEFINIR V1,V2,D,Th,Tmin COMO REAL;
	ESCRIBIR"INGRESAR LA VELOCIDAD DEL VEHICULO MAS RAPIDO";
	LEER V1;
	ESCRIBIR"INGRESAR LA VELOCIDAD DEL OTRO VEHICULO";
	LEER V2;
	ESCRIBIR "INGRESAR LA DISTACIA QUE HAY ENTRE AMBOS VEHICULOS";
	LEER D;
	Th<-D/(V1-V2);
	Tmin<-TRUNC(Th*60);
	ESCRIBIR "EL TIEMPO EN QUE ALCANZARÁ EL VEHICULO MAS RAPIDO AL OTRO ES DE ",Tmin," MINUTOS";
	
FinAlgoritmo
