Algoritmo EJE15
	DEFINIR VARIABLE_A,VARIABLE_B,CONTROL COMO ENTERO;
	ESCRIBIR "INGRESAR EL VALOR DE A";
	LEER VARIABLE_A;
	ESCRIBIR "INGRESAR EL VALOR DE B";
	LEER VARIABLE_B;
	CONTROL=VARIABLE_A;
	VARIABLE_A=VARIABLE_B;
	VARIABLE_B=CONTROL;
	ESCRIBIR "EL VALOR DE A ES: ",VARIABLE_A;
	ESCRIBIR "EL VALOR DE B ES: ",VARIABLE_B;
FinAlgoritmo
