Algoritmo EJE13
	DEFINIR N1,RES1,RES2 Como REAL;
	ESCRIBIR "INGRESASR UN NÚMERO";
	LEER N1;
	RES1=RAIZ(N1);
	RES2=N1^(1/3);
	ESCRIBIR" LA RAIZ CUADRADA DE ",N1," ES DE: ",RES1;
	ESCRIBIR "LA RAIZ CUBICA DE ",N1," ES DE: ",RES2;
	
	
	
	
FinAlgoritmo
