Algoritmo HIPOTENUSA
	DEFINIR BASE,h,HIPO Como Real;
	ESCRIBIR "INGRESAR LA BASE DE SU TRIANGULO"
	LEER BASE;
	ESCRIBIR "INGRESE LA ALTURA DE SU TRIANGULO"
	LEER h
	HIPO<-raiz(BASE^2+H^2)
	ESCRIBIR "LA HIPOTENUSA DE SU TRIÁNGULO ES DE: ",HIPO;
FinAlgoritmo
