Algoritmo MULTIPLES_EJERCICIOS
	DEFINIR N1,N2,SUM,REST,MULT,DIV Como Real;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N1;
	ESCRIBIR "INGRESAR UN NÚMERO";
	LEER N2;
	SUM<-N1+N2
	REST<-N1-N2
	MULT<-N1*N2
	DIV<-N1/N2
	ESCRIBIR "LA SUMA ENTRE ",N1," Y ",N2," ES DE: ",SUM;
	ESCRIBIR "LA RESTA ENTRE ",N1," Y ",N2," ES DE: ",REST;
	ESCRIBIR "LA MULTIPLICACIÓN ENTRE ",N1," Y ",N2," ES DE: ",MULT;
	ESCRIBIR "LA DIVISIÓN ENTRE ",N1," Y ",N2," ES DE: ",DIV;
FinAlgoritmo
