Algoritmo PERIMETRO_ÁREA_DE_UN_RECTÁNGULO
	DEFINIR base,h,ÁREA,PERIM Como Real
	ESCRIBIR "INGRESAR LA BASE DE SU RECTÁNGULO"
	LEER base;
	ESCRIBIR "INGRESE LA ALTURA DE SU RECTÁNGULO"
	LEER h;
	ÁREA<-base*h;
	PERIM<-2*(base+h);
	ESCRIBIR "EL ÁREA DE SU RECTÁNGULO ES DE: ",ÁREA;
	ESCRIBIR "EL PERIMETRO DE SU RECTÁNGULO ES DE: ",PERIM;
FinAlgoritmo
