Algoritmo TEMPERATURA
	DEFINIR F,C COMO REAL
	ESCRIBIR "INGRESE LA TEMPERATURA EN FAHRENHEIT A CONVERTIR"
	LEER F
	C<-(F-32)*5/9
	ESCRIBIR "EL EQUIVALENTE DE ",F,"°F A °C ES DE: ",C,"°C";
FinAlgoritmo
